# Telco Customer Churn

In [1]:
# set task name
task_name = 'telco_churn-v2'

# load common
%run common.ipynb

Cortex Python SDK v6.2.0a1
Cortex Discovery Libraries v3.5.14

## Data Selection
Data selection uses the `Transition` capability

In [2]:
from ds_discovery import Transition

In [3]:
tr = Transition.from_env(task_name, has_contract=False)
tr.set_source_uri('s3://lk-datasets/kaggle/Telco_customer_churn.csv')

tr.set_persist(tr.pm.file_pattern(name='select', prefix='Telco-Customer-Churn', file_type='parquet'))
tr.set_description("Telco Churn Dataset")

In [4]:
df = tr.load_source_canonical()

In [5]:
tr.canonical_report(df, stylise=False)

,Attributes (52),dType,%_Null,%_Dom,Count,Unique,Observations
0,Age,int64,0.000,0.022,7043,62,max=80 | min=19 | mean=46.51 | dominant=42
1,Avg Monthly GB Download,int64,0.000,0.217,7043,50,max=85 | min=0 | mean=20.52 | dominant=0
2,Avg Monthly Long Distance Charges,float64,0.000,0.097,7043,3584,max=49.99 | min=0.0 | mean=22.96 | dominant=0.0
3,CLTV,int64,0.000,0.001,7043,3438,max=6500 | min=2003 | mean=4400.3 | dominant=5546
4,Churn,object,0.000,0.735,7043,2,Sample: No | Yes
5,Churn Category,object,0.000,0.735,7043,6,Sample: 0 | Competitor | Attitude | Dissatisfaction | Price
6,Churn Reason,object,0.735,0.735,7043,21,Sample: Attitude of support person | Competitor offered higher download speeds | Competitor offered ...
7,Churn Score,int64,0.000,0.021,7043,85,max=100 | min=5 | mean=58.7 | dominant=80
8,Churn Score.1,int64,0.000,0.029,7043,81,max=96 | min=5 | mean=58.51 | dominant=91
9,City,object,0.000,0.043,7043,1129,Sample: Los Angeles | San Diego | San Jose | Sacramento | San Francisco
10,Contract,object,0.000,0.550,7043,3,Sample: Month-to-month | Two year | One year
11,Count,int64,0.000,1.000,7043,1,max=1 | min=1 | mean=1.0 | dominant=1
12,Country,object,0.000,1.000,7043,1,Sample: United States
13,Customer Status,object,0.000,0.670,7043,3,Sample: Stayed | Churned | Joined
14,Dependents,object,0.000,0.700,7043,2,Sample: No | Yes
15,DeviceProtection,object,0.000,0.439,7043,3,Sample: No | Yes | No internet service
16,InternetService,object,0.000,0.440,7043,3,Sample: Fiber optic | DSL | No
17,Lat Long,object,0.000,0.001,7043,1652,"Sample: 33.964131, -118.272783 | 34.152875, -118.486056 | 32.912664, -116.635387 | 32.64164, -116.98..."
18,Latitude,float64,0.000,0.001,7043,1652,"max=41.962127 | min=32.555828 | mean=36.28 | dominant=[32.555828, 32.578103]"
19,Longitude,float64,0.000,0.001,7043,1651,max=-114.192901 | min=-124.301372 | mean=-119.8 | dominant=-121.994813
20,Married,object,0.000,0.517,7043,2,Sample: No | Yes
21,MonthlyCharges,float64,0.000,0.009,7043,1585,max=118.75 | min=18.25 | mean=64.76 | dominant=20.05
22,MultipleLines,object,0.000,0.481,7043,3,Sample: No | Yes | No phone service
23,Number of Referrals,int64,0.000,0.543,7043,12,max=11 | min=0 | mean=1.95 | dominant=0
24,Offer,object,0.000,0.550,7043,6,Sample: None | Offer B | Offer E | Offer D | Offer A
25,OnlineBackup,object,0.000,0.438,7043,3,Sample: No | Yes | No internet service
26,OnlineSecurity,object,0.000,0.497,7043,3,Sample: No | Yes | No internet service
27,PaperlessBilling,object,0.000,0.592,7043,2,Sample: Yes | No
28,Partner,object,0.000,0.517,7043,2,Sample: No | Yes
29,PaymentMethod,object,0.000,0.336,7043,4,Sample: Electronic check | Mailed check | Bank transfer (automatic) | Credit card (automatic)
30,PhoneService,object,0.000,0.903,7043,2,Sample: Yes | No
31,Premium Tech Support,object,0.000,0.710,7043,2,Sample: No | Yes
32,Referred a Friend,object,0.000,0.543,7043,2,Sample: No | Yes
33,Satisfaction Score,int64,0.000,0.378,7043,5,max=5 | min=1 | mean=3.24 | dominant=3
34,SeniorCitizen,int64,0.000,0.838,7043,2,max=1 | min=0 | mean=0.16 | dominant=0
35,State,object,0.000,1.000,7043,1,Sample: California
36,Streaming Music,object,0.000,0.647,7043,2,Sample: No | Yes
37,StreamingMovies,object,0.000,0.395,7043,3,Sample: No | Yes | No internet service
38,StreamingTV,object,0.000,0.399,7043,3,Sample: No | Yes | No internet service
39,TechSupport,object,0.000,0.493,7043,3,Sample: No | Yes | No internet service
40,Total Extra Data Charges,int64,0.000,0.897,7043,16,max=150 | min=0 | mean=6.86 | dominant=0
41,Total Long Distance Charges,float64,0.000,0.097,7043,6087,max=3564.72 | min=0.0 | mean=749.1 | dominant=0.0
42,Total Refunds,float64,0.000,0.925,7043,500,max=49.79 | min=0.0 | mean=1.96 | dominant=0.0
43,Total Revenue,float64,0.000,0.000,7043,6982,"max=11979.34 | min=21.36 | mean=3034.38 | dominant=[24.8, 66.56]"
44,TotalCharges,object,0.000,0.002,7043,6531,Sample: 20.2 | | 19.75 | 19.65 | 20.05
45,Under 30,object,0.000,0.801,7043,2,Sample: No | Yes
46,Unlimited Data,object,0.000,0.674,7043,2,Sample: Yes | No
47,Zip Code,int64,0.000,0.001,7043,1652,"max=96161 | min=90001 | mean=93521.96 | dominant=[90001, 90002]"
48,churn_rate,int64,0.000,0.735,7043,2,max=1 | min=0 | mean=0.27 | dominant=0
49,customerID,object,0.000,0.000,7043,7043,Sample: 3668-QPYBK | 9169-BSVIN | 0206-OYVOC | 6418-HNFED | 8805-JNRAZ
50,gender,object,0.000,0.505,7043,2,Sample: Male | Female
51,tenure,int64,0.000,0.087,7043,73,max=72 | min=0 | mean=32.37 | dominant=1

In [6]:
# select and type from observations
df = tr.tools.auto_clean_header(df, rename_map={'customerID': 'CustomerID', 'gender': 'Gender', 'tenure': 'Tenure','churn_rate':"ChurnRate"})
df = tr.tools.to_float_type(df, headers='TotalCharges')

In [8]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,ChurnRate,Churn_Score,CLTV,Churn_Reason,Count,Country,State,City,Zip_Code,Lat_Long,Latitude,Longitude,Age,Under_30,Married,Referred_a_Friend,Number_of_Referrals,Offer,Avg_Monthly_Long_Distance_Charges,Avg_Monthly_GB_Download,Streaming_Music,Premium_Tech_Support,Unlimited_Data,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Satisfaction_Score,Customer_Status,Churn_Score.1,Churn_Category
0,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.850,108.150,Yes,1,86,3239,Competitor made better offer,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964,-118.273,37,No,No,No,0,None,10.470,21,No,No,Yes,0.000,0,20.940,129.090,1,Churned,86,Competitor
1,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.700,151.650,Yes,1,67,2701,Moved,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059,-118.307,19,Yes,No,No,0,None,9.120,51,No,No,Yes,0.000,0,18.240,169.890,2,Churned,67,Other
2,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.650,820.500,Yes,1,86,5372,Moved,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048,-118.294,31,No,No,No,0,None,12.150,26,Yes,No,Yes,0.000,0,97.200,917.700,3,Churned,86,Other
3,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.800,3046.050,Yes,1,84,5003,Moved,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062,-118.316,23,Yes,Yes,No,0,Offer C,4.890,47,Yes,Yes,Yes,0.000,0,136.920,3182.970,3,Churned,84,Other
4,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.700,5036.300,Yes,1,89,5340,Competitor had better devices,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039,-118.266,38,No,No,No,0,None,44.330,11,Yes,No,Yes,0.000,0,2172.170,7208.470,1,Churned,89,Competitor

In [9]:
# turn yes/no to bool to guarantee 0/1 distribution
yn = []
for col in df.columns:
    if df[col].nunique() == 2 and 'Yes' in df[col].unique().tolist():
        yn.append(col)
df = tr.tools.to_bool_type(df, headers=yn, bool_map={'Yes': True})

In [11]:
# run the pipeline  
tr.run_component_pipeline()

In [12]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,ChurnRate,Churn_Score,CLTV,Churn_Reason,Count,Country,State,City,Zip_Code,Lat_Long,Latitude,Longitude,Age,Under_30,Married,Referred_a_Friend,Number_of_Referrals,Offer,Avg_Monthly_Long_Distance_Charges,Avg_Monthly_GB_Download,Streaming_Music,Premium_Tech_Support,Unlimited_Data,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Satisfaction_Score,Customer_Status,Churn_Score.1,Churn_Category
0,3668-QPYBK,Male,0,False,False,2,True,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,True,Mailed check,53.850,108.150,True,1,86,3239,Competitor made better offer,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964,-118.273,37,False,False,False,0,None,10.470,21,False,False,True,0.000,0,20.940,129.090,1,Churned,86,Competitor
1,9237-HQITU,Female,0,False,False,2,True,No,Fiber optic,No,No,No,No,No,No,Month-to-month,True,Electronic check,70.700,151.650,True,1,67,2701,Moved,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059,-118.307,19,True,False,False,0,None,9.120,51,False,False,True,0.000,0,18.240,169.890,2,Churned,67,Other
2,9305-CDSKC,Female,0,False,False,8,True,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,True,Electronic check,99.650,820.500,True,1,86,5372,Moved,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048,-118.294,31,False,False,False,0,None,12.150,26,True,False,True,0.000,0,97.200,917.700,3,Churned,86,Other
3,7892-POOKP,Female,0,True,False,28,True,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,True,Electronic check,104.800,3046.050,True,1,84,5003,Moved,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062,-118.316,23,True,True,False,0,Offer C,4.890,47,True,True,True,0.000,0,136.920,3182.970,3,Churned,84,Other
4,0280-XJGEX,Male,0,False,False,49,True,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,True,Bank transfer (automatic),103.700,5036.300,True,1,89,5340,Competitor had better devices,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039,-118.266,38,False,False,False,0,None,44.330,11,True,False,True,0.000,0,2172.170,7208.470,1,Churned,89,Competitor

In [13]:
df.shape

(7043, 52)